---
title: "strawberries"
author: "Yuan Wang"
format: html
editor: visual
---

```{r, message=FALSE, warning=FALSE}
# https://quickstats.nass.usda.gov/
library(tidyverse)
library(tidyr)
library(stringr)
library(knitr)
library(dplyr)

# str_detect
# str_replace()
```

```{r}
s <- read.csv("strawberry_10oct25.csv")
f <- read.csv("fertilizers.csv")
```

```{r}
strawberry <- s |>
  select(where(~ !(all(is.na(.x)) || length(unique(na.omit(.x))) == 1)))
```

```{r}
#| label: column cleaning

# removing extra words
strawberry$Data.Item <- strawberry$Data.Item |>
  str_remove("^STRAWBERRIES - ")

## creating an Acres column
strawberry <- strawberry |> 
  mutate(Acres = ifelse(str_starts(Data.Item, "ACRES"),
                        str_remove(Data.Item, "^ACRES\\s+"),
                        NA_character_))
## creating an Operations column
strawberry <- strawberry |> 
  mutate(Operations = ifelse(str_starts(Data.Item, "OPERATIONS"),
                        str_remove(Data.Item, "^OPERATIONS\\s+"),
                        NA_character_))

strawberry$Operations <- strawberry$Operations |>
  str_remove("^WITH ")
rm(s, f)
```

```{r}
#| label: census data 

census <- strawberry |>
  filter(Program == "CENSUS")
```

```{r}
#| label: survey data 

survey <- strawberry |> 
   filter(Program == "SURVEY")
```

```{r}
#| label: california

calif <- strawberry |>
  filter(State == "CALIFORNIA")
```

```{r}
#| label: census by state
```

```{r}
#| label: survey by state
```

```{r}
#| label: explore organization

state_all <- strawberry %>%  distinct(State)
state_all1 <- strawberry %>% group_by(State) %>% count()

calif <- fertilizer |> filter(State == "CALIFORNIA")
census <- fertilizer |> filter(Program == "CENSUS")
survey <- fertilizer |> filter(Program == "SURVEY")

#every row is associated with state 
#if(sum(state_all$n) == dim(strawberry)[1]{print("Yes every row in the data is associated with a state.")}
```

```{r}
#| label: drop one value columns 

```

```{r}
# calif <- strawberry |> 
#   filter(State == "CALIFORNIA")

```

```{r}
#| label: name
```

```{r, message=FALSE}
#notes from class today
library(rnassqs)
library(tidyverse)
library(stringr)

params <- list(commodity_desc = "CORN",
               year = 2012,
               agg_level_des = "STATE",
               state_alpha = "WA",
               statisticcat_desc = "YIELD")

response <- nassqs_GET(params)
yield <- nassqs_parse(response)
```
